import localFont from "next/font/local";
import "maplibre-gl/dist/maplibre-gl.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import dynamic from "next/dynamic";

const NextProgress = dynamic(() => import("@/components/next-progress-bar"), {
  ssr: false,
});

const halenoir = localFont({
  src: [
    {
      path: "../assets/fonts/Halenoir-Black.otf",
      weight: "800",
    },
    {
      path: "../assets/fonts/Halenoir-Bold.otf",
      weight: "700",
    },
    {
      path: "../assets/fonts/Halenoir-DemiBold.otf",
      weight: "600",
    },
    {
      path: "../assets/fonts/HalenoirCompactText-Medium.otf",
      weight: "500",
    },
    {
      path: "../assets/fonts/HalenoirCompactText-Regular.otf",
      weight: "400",
    },
    {
      path: "../assets/fonts/HalenoirCompact-ExtraLight.otf",
      weight: "300",
    },
  ],
  variable: "--font-halenoir",
});

export const metadata: Metadata = {
  title: "OnTrack Logistic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${halenoir.className}`}>
        <NextProgress />
        {children}
        <ToastContainer
          position="bottom-right"
          autoClose={3500}
          hideProgressBar
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable={false}
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
